src/ShareCare.App/Controllers/PatientGuideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareCare.App.Extensions;
using ShareCare.Model.Interfaces;
using System;
using System.Threading.Tasks;

namespace ShareCare.App.Controllers
{
    [Authorize]
    public class PatientGuideController : Controller
    {
        private readonly IPatientGuideService patientGuideService;

        public PatientGuideController(IPatientGuideService patientGuideService)
        {
            this.patientGuideService = patientGuideService;
        }

        public async Task<IActionResult> Index()
        {
            var identifier = HttpContext.GetIdentifier();
            var patients = await patientGuideService.GetListAsync(identifier);
            return View(patients);
        }

        public IActionResult Details(Guid id)
        {
            //todo analise metrica paciente
            return View();
        }

        public async Task<IActionResult> Historic(Guid id)
        {
            var historic = await patientGuideService.GetHistoricAsync(id);
            return View(historic);
        }
    }
}

src/ShareCare.App/Controllers/SchedulerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareCare.App.Extensions;
using ShareCare.Model.Enums;
using ShareCare.Model.Interfaces;
using ShareCare.Model.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ShareCare.App.Controllers
{
    [Authorize]
    public class SchedulerController : Controller
    {
        private readonly ISchedulerService schedulerService;

        public SchedulerController(ISchedulerService schedulerService)
        {
            this.schedulerService = schedulerService;
        }


        public IActionResult Index(Guid id, PersonType shedulertype, string specialties)
        {
            var scheduler = new SchedulerModel();
            scheduler.DoctorPatient = new DoctorPatientModel();
            scheduler.DateStart = DateTime.Now.AddHours(1);
            scheduler.DateEnd = DateTime.Now.AddHours(2);

            if (shedulertype == PersonType.Doctor)
            {
                scheduler.DoctorPatient.DoctorId = id;
                scheduler.Specialties = specialties.Split(",").ToList();
                scheduler.DoctorPatient.PatientId = Guid.Parse(HttpContext.GetIdentifier());
                scheduler.Type = SchedulerType.Scheduler;
            }
            else
            {
                scheduler.DoctorPatient.PatientId = id;
                scheduler.DoctorPatient.DoctorId = Guid.Parse(HttpContext.GetIdentifier());
                scheduler.Type = SchedulerType.Solicitation;
                scheduler.Specialties = specialties.Split(",").ToList();
            }

            return View(scheduler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SchedulerModel scheduler)
        {
            if (ModelState.IsValid)
            {
                var schedulervalidator = await schedulerService.CreateAsync(scheduler);
                if (!schedulervalidator.Item1.Any())
                {
                    if (scheduler.Type == SchedulerType.Scheduler)
                    {
                        return RedirectToAction(nameof(DetailScheduler), new { schedulerId = schedulervalidator.Item2 });
                    }
                    else
                    {
                        return RedirectToAction(nameof(DetailSolicitation), new { schedulerId = schedulervalidator.Item2 });
                    }
                }
            }

            return View(scheduler);
        }

        public async Task<IActionResult> DetailScheduler(Guid schedulerId)
        {
            var scheduler = await schedulerService.GetConfirmSchedulerAsync(schedulerId);
            return View(scheduler);
        }

        public async Task<IActionResult> DetailSolicitation(Guid schedulerId)
        {
            var solicitation = await schedulerService.GetConfirmSolicitationAsync(schedulerId);
            return View(solicitation);
        }
    }
}

src/ShareCare.App/Views/Scheduler/ConfirmScheduler.cshtml
@model ShareCare.Model.Models.ConfirmSchedulerModel

@{
    ViewData["Title"] = "ConfirmScheduler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    h4 {
        top: 99px;
        left: 415px;
        width: 440px;
        height: 35px;
        color: var(--unnamed-color-ffffff);
        text-align: left;
        font: normal normal bold 25px/38px Poppins;
        letter-spacing: 0px;
        color: #FFFFFF;
        opacity: 1;
    }

    h5 {
        top: 139px;
        left: 415px;
        width: 800px;
        height: 28px;
        color: var(--unnamed-color-ffffff);
        text-align: left;
        font: normal normal normal 20px/30px Poppins;
        letter-spacing: 0px;
        color: #FFFFFF;
        opacity: 1;
    }

    th {
        top: 221px;
        left: 525px;
        width: 43px;
        height: 20px;
        text-align: left;
        font: normal normal bold 14px/21px Poppins;
        letter-spacing: 0px;
        color: #3D3D3D;
        opacity: 1;
    }

    tr {
        top: 251px;
        left: 440px;
        width: 771px;
        height: 121px;
        background: var(--unnamed-color-ffffff) 0% 0% no-repeat padding-box;
        background: #FFFFFF 0% 0% no-repeat padding-box;
        box-shadow: 0px 3px 6px #00000029;
        opacity: 1;
    }
</style>

<div class="col-md-12">
    <div class="table-data__tool">
        <div class="table-data__tool-right">
            <h4 style="color: white; top: 99px;">Meu calendário de atendimentos:</h4>
            <h5 style="color:white; top:139px;">Aqui você controla toda a sua rotina de cuidados com seus pacientes</h5>
        </div>
    </div>
    <div class="col">
        <div class="au-card">
            <div class="row row-cols-1">
                <div class="col-1" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary"><</button>
                    <button type="button" class="btn btn-outline-secondary">></button>
                </div>
                <div class="col-1" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary">Hoje</button>
                </div>
                <div class="col-7" style="text-align: center;">
                    <p style="color:black; text-align: center; font-size:larger">Sábado - 5 de Setembro, 2020</p>
                </div>
                <div class="col-3" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary" style="color:#F46A79">Mês</button>
                    <button type="button" class="btn btn-outline-secondary" style="color:#F46A79">Semana</button>
                    <button type="button" class="btn btn-outline-secondary">Dia</button>
                </div>
            </div>
            <br />
            <h5 style="color:black;">Consulta de rotina</h5>
            <br />
            <div class="au-card">
                <div class="card">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <table class="table table-data2">
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="image img-40">
                                            <img src="~/img/icon/Gabriela.jpg" />
                                        </div>
                                    </td>
                                    <td>
                                        <span style="font: normal normal bold 18px/27px Poppins;letter-spacing: 0px;color: #002D42;opacity: 1;">@Html.DisplayFor(model => model.DoctorName)</span>
                                         <br />@Html.DisplayFor(model => model.Specialty)
                                    </td>
                                    <td class="desc">
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <br />
                <h6>@Html.DisplayNameFor(model => model.Description)</h6>
                <br />
                <div class="card">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <h6 class="desc" style="text-align:center;font-size:larger">
                            Endereço da consulta
                        </h6>
                        <br />
                        <h6 class="desc" style="text-align:center; color:#F46A79;font-size:larger">
                            @Html.DisplayFor(model => model.MeetAddressLink)
                        </h6>
                        <br />
                        <h6 class="desc" style="text-align:center">
                            <button type="button" class="btn btn-outline-secondary" style="align-content:center">Copiar</button>
                        </h6>
                        <br />
                    </form>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">
                    <div class="row row-cols-3">
                        <div class="col" style="color:#F46A79">Anotações do médico</div>
                        <div class="col">Receitas</div>
                        <div class="col">Exames</div>
                        <div class="col">Atestados</div>
                        <div class="col">Sintomas</div>
                        <div class="col">Analytics</div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <br />
                        <div class="row form-group">
                            <div class="col-12 col-md-12">
                                @Html.DisplayFor(model => model.Description)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/ShareCare.App/Views/Scheduler/DetailScheduler.cshtml
@model ShareCare.Model.Models.DetailSchedulerModel

@{
    ViewData["Title"] = "ConfirmScheduler";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var healthHistory = Model.Enchiridions.SingleOrDefault(x => x.Type == EnchiridionType.HealthHistory);
}


<style>
    h4 {
        top: 99px;
        left: 415px;
        width: 440px;
        height: 35px;
        color: var(--unnamed-color-ffffff);
        text-align: left;
        font: normal normal bold 25px/38px Poppins;
        letter-spacing: 0px;
        color: #FFFFFF;
        opacity: 1;
    }

    h5 {
        top: 139px;
        left: 415px;
        width: 800px;
        height: 28px;
        color: var(--unnamed-color-ffffff);
        text-align: left;
        font: normal normal normal 20px/30px Poppins;
        letter-spacing: 0px;
        color: #FFFFFF;
        opacity: 1;
    }

    th {
        top: 221px;
        left: 525px;
        width: 43px;
        height: 20px;
        text-align: left;
        font: normal normal bold 14px/21px Poppins;
        letter-spacing: 0px;
        color: #3D3D3D;
        opacity: 1;
    }

    tr {
        top: 251px;
        left: 440px;
        width: 771px;
        height: 121px;
        background: var(--unnamed-color-ffffff) 0% 0% no-repeat padding-box;
        background: #FFFFFF 0% 0% no-repeat padding-box;
        box-shadow: 0px 3px 6px #00000029;
        opacity: 1;
    }
</style>

<div class="col-md-12">
    <div class="table-data__tool">
        <div class="table-data__tool-right">
            <h4 style="color: white; top: 99px;">Meu calendário de atendimentos:</h4>
            <h5 style="color:white; top:139px;">Aqui você controla toda a sua rotina de cuidados com seus pacientes</h5>
        </div>
    </div>
    <div class="col">
        <div class="au-card">
            <div class="row row-cols-1">
                <div class="col-1" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary"><</button>
                    <button type="button" class="btn btn-outline-secondary">></button>
                </div>
                <div class="col-1" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary">Hoje</button>
                </div>
                <div class="col-7" style="text-align: center;">
                    <p style="color:black; text-align: center; font-size:larger">Sábado - 5 de Setembro, 2020</p>
                </div>
                <div class="col-3" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary" style="color:#F46A79">Mês</button>
                    <button type="button" class="btn btn-outline-secondary" style="color:#F46A79">Semana</button>
                    <button type="button" class="btn btn-outline-secondary">Dia</button>
                </div>
            </div>
            <br />
            <h5 style="color:black;">Consulta de rotina</h5>
            <br />
            <div class="au-card">
                <div class="card">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <table class="table table-data2">
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="image img-40">
                                            <img src="~/img/icon/Gabriela.jpg" />
                                        </div>
                                    </td>
                                    <td>
                                        <span style="font: normal normal bold 18px/27px Poppins;letter-spacing: 0px;color: #002D42;opacity: 1;">@Html.DisplayFor(model => model.DoctorName)</span>
                                        <br />@Html.DisplayFor(model => model.Specialty)
                                    </td>
                                    <td class="desc">
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <br />
                <h6>@Html.DisplayNameFor(model => model.Description)</h6>
                <br />
                <div class="card" style="background-color:#E4E4E4">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <h6 class="desc" style="text-align:center;font-size:larger; font: normal normal normal 14px/21px Poppins;">
                            Endereço da consulta:
                        </h6>
                        <br />
                        <h6 class="desc" style="text-align:center; color:#F46A79;font-size:larger">
                            @Html.DisplayFor(model => model.MeetAddressLink)
                        </h6>
                        <br />
                        <h6 class="desc" style="text-align:center">
                            <i class="fas fa-files-o fa-2x" style="color:#1CA5B8; border: none"></i> <span style="font: normal normal normal 14px/21px Poppins;">Copiar</span>
                            @*<button type="button" class="btn btn-outline-secondary" style="align-content:center; background-color:#1CA5B8">Copiar</button>*@
                        </h6>
                        <br />
                    </form>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">
                    <div class="row row-cols-3">
                        <div class="col" style="color:black;font: normal normal bold 16px/25px Poppins;">Anotações do médico</div>
                        <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Receitas</div>
                        <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Exames</div>
                        <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Atestados</div>
                        <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Sintomas</div>
                        <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Analytics</div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <br />
                        <div class="row form-group">
                            <br />
                        <div class="col-12 col-md-12">
                            @healthHistory?.Value
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

src/ShareCare.App/Views/Scheduler/DetailSolicitation.cshtml
@model ShareCare.Model.Models.DetailSolicitationModel

@{
    ViewData["Title"] = "ConfirmSolicitation";
    Layout = "~/Views/Shared/_Layout.cshtml";

    CultureInfo culture = new CultureInfo("pt-Br");
    var datalong = Model.DateStart.ToString(culture.DateTimeFormat.LongDatePattern, culture);
    var dayofweek = Model.DayOfWeek.ToString(culture);

}

    <style>
        h4 {
            top: 99px;
            left: 415px;
            width: 440px;
            height: 35px;
            color: var(--unnamed-color-ffffff);
            text-align: left;
            font: normal normal bold 25px/38px Poppins;
            letter-spacing: 0px;
            color: #FFFFFF;
            opacity: 1;
        }

        h5 {
            top: 139px;
            left: 415px;
            width: 800px;
            height: 28px;
            color: var(--unnamed-color-ffffff);
            text-align: left;
            font: normal normal normal 20px/30px Poppins;
            letter-spacing: 0px;
            color: #FFFFFF;
            opacity: 1;
        }

        th {
            top: 221px;
            left: 525px;
            width: 43px;
            height: 20px;
            text-align: left;
            font: normal normal bold 14px/21px Poppins;
            letter-spacing: 0px;
            color: #3D3D3D;
            opacity: 1;
        }

        tr {
            top: 251px;
            left: 440px;
            width: 771px;
            height: 121px;
            background: var(--unnamed-color-ffffff) 0% 0% no-repeat padding-box;
            background: #FFFFFF 0% 0% no-repeat padding-box;
            box-shadow: 0px 3px 6px #00000029;
            opacity: 1;
        }
    </style>

<div class="col-md-12">
    <div class="table-data__tool">
        <div class="table-data__tool-right">
            <h4 style="color: white; top: 99px;">Meu calendário de atendimentos:</h4>
            <h5 style="color:white; top:139px;">Aqui você controla toda a sua rotina de cuidados com seus pacientes</h5>
        </div>
    </div>
    <div class="col">
        <div class="au-card">
            <div class="row row-cols-1">
                <div class="col-1" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary"><</button>
                    <button type="button" class="btn btn-outline-secondary">></button>
                </div>
                <div class="col-1" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary">@dayofweek</button>
                </div>
                <div class="col-7" style="text-align: center;">

                    <p style="color:black; text-align: center; font-size:larger"> @datalong</p>
                </div>
                <div class="col-3" style="align-content:center">
                    <button type="button" class="btn btn-outline-secondary" style="color:#F46A79">Mês</button>
                    <button type="button" class="btn btn-outline-secondary" style="color:#F46A79">Semana</button>
                    <button type="button" class="btn btn-outline-secondary">Dia</button>
                </div>
            </div>
            <br />
            <h4 style="color:black;">Ficha de consulta</h4>
            <br />
            <div class="au-card">
                <div class="row row-cols-1">
                    <div class="col">
                        <div class="rs-select2--light rs-select2--sm">
                            <select class="js-select2" name="time">
                                <option selected="selected">Nome</option>
                                <option value="">Juliane Gonçalves Ribeiro</option>
                                <option value="">Gabriela Saori</option>
                            </select>
                            <div class="dropDownSelect2"></div>
                        </div>
                        <div class="rs-select2--light rs-select2--sm">
                            <select class="js-select2" name="time">
                                <option selected="selected">Email</option>
                                <option value="">juliane@gmail.com</option>
                                <option value="">a_bittencourt86@gmail.com</option>
                            </select>
                            <div class="dropDownSelect2"></div>
                        </div>
                        <div class="rs-select2--light rs-select2--sm">
                            <select class="js-select2" name="time">
                                <option selected="selected">Consulta</option>
                                <option value="">Cardiologia</option>
                                <option value="">Pediatria</option>
                            </select>
                            <div class="dropDownSelect2"></div>
                        </div>
                        <div class="rs-select2--light rs-select2--sm">
                            <select class="js-select2" name="time">
                                <option selected="selected">Horários</option>
                                <option value="">06/09/2020</option>
                                <option value="">07/09/2020</option>
                                <option value="">08/09/2020</option>
                                <option value="">09/09/2020</option>
                            </select>
                            <div class="dropDownSelect2"></div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="card">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <table class="table table-data2">
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="image img-40">
                                            <img src="~/img/icon/Juliane.jpg" />
                                        </div>
                                    </td>
                                    <td class="desc" style="color:black">
                                        @Html.DisplayFor(model => model.PatientName)
                                    </td>
                                    <td class="desc" style="color:black">
                                        juliane@goncalves.com.br
                                    </td>
                                    <td class="desc" style="color:black">
                                        @Html.DisplayFor(model => model.Specialty)
                                    </td>
                                    <td class="desc">
                                        @Html.ActionLink("", "Details", "PatientGuide", new { id = Model.PatientId }, new { @style = "margin:10px; color: #1CA5B8;top: 299px;left: 1087px;width: 32px;height: 24px;", @class = "fas fa-chart-bar fa-2x" })
                                        @Html.ActionLink("", "Historic", "PatientGuide", new { id = Model.PatientId }, new { @style = "margin:10px; color: #1CA5B8;top: 443px;left: 1136px;width: 21px;height: 24px;", @class = "fas fa-book fa-2x" })
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
                <br />
                <h6>@Html.DisplayNameFor(model => model.Description)</h6>
                <br />
                <div class="card" style="background-color:#E4E4E4">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <h6 class="desc" style="text-align:center;font-size:larger; font: normal normal normal 14px/21px Poppins;">
                            Endereço da consulta
                        </h6>
                        <br />
                        <h6 class="desc" style="text-align:center; color:#F46A79;font-size:larger">
                            @Html.DisplayFor(model => model.MeetAddressLink)
                        </h6>
                        <br />
                        <h6 class="desc" style="text-align:center">
                            <i class="fas fa-files-o fa-2x" style="color:#1CA5B8; border: none"></i> <span style="font: normal normal normal 14px/21px Poppins;">Copiar</span>
                            @*<button type="button" class="btn btn-outline-secondary" style="align-content:center;  background-color:#1CA5B8">Copiar</button>*@
                        </h6>
                        <br />
                    </form>
                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="row row-cols-3">
                            <div class="col" style="color:black;font: normal normal bold 16px/25px Poppins;">Anotações do médico</div>
                            <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Receitas Online</div>
                            <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Guia do exame</div>
                            <div class="col" style="font: normal normal bold 16px/25px Poppins;color: #B7B7B7;">Atestado</div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body card-block">
                            <div class="col-12">
                                <textarea name="textarea-input" id="textarea-input" rows="9" placeholder="Adicione Comentários da Consulta" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>