src/ShareCare.App/Controllers/MedicalGuideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareCare.Model.Enums;
using ShareCare.Model.Interfaces;
using System.Threading.Tasks;

namespace ShareCare.App.Controllers
{
    [Authorize]
    public class MedicalGuideController : Controller
    {
        private readonly IMedicalGuideService guideService;

        public MedicalGuideController(IMedicalGuideService guideService)
        {
            this.guideService = guideService;
        }

        public async Task<IActionResult> Index()
        {
            var doctors = await guideService.GetListAsync();
            return View(doctors);
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

src/ShareCare.App/Controllers/PatientGuideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareCare.App.Extensions;
using ShareCare.Model.Interfaces;
using System;
using System.Threading.Tasks;

namespace ShareCare.App.Controllers
{
    [Authorize]
    public class PatientGuideController : Controller
    {
        private readonly IPatientGuideService patientGuideService;

        public PatientGuideController(IPatientGuideService patientGuideService)
        {
            this.patientGuideService = patientGuideService;
        }

        public async Task<IActionResult> Index()
        {
            var identifier = HttpContext.GetIdentifier();
            var patients = await patientGuideService.GetListAsync(identifier);
            return View(patients);
        }

        public IActionResult Details(Guid id)
        {
            //todo analise metrica paciente
            return View();
        }

        public async Task<IActionResult> Historic(Guid id)
        {
            var historic = await patientGuideService.GetHistoricAsync(id);
            return View(historic);
        }
    }
}

src/ShareCare.App/Controllers/SchedulerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareCare.App.Extensions;
using ShareCare.Model.Enums;
using ShareCare.Model.Interfaces;
using ShareCare.Model.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ShareCare.App.Controllers
{
    [Authorize]
    public class SchedulerController : Controller
    {
        private readonly ISchedulerService schedulerService;

        public SchedulerController(ISchedulerService schedulerService)
        {
            this.schedulerService = schedulerService;
        }


        public IActionResult Index(Guid id, PersonType shedulertype, string specialties)
        {
            var scheduler = new SchedulerModel();
            scheduler.DoctorPatient = new DoctorPatientModel();
            scheduler.DateStart = DateTime.Now.AddHours(1);
            scheduler.DateEnd = DateTime.Now.AddHours(2);

            if (shedulertype == PersonType.Doctor)
            {
                scheduler.DoctorPatient.DoctorId = id;
                scheduler.Specialties = specialties.Split(",").ToList();
                scheduler.DoctorPatient.PatientId = Guid.Parse(HttpContext.GetIdentifier());
                scheduler.Type = SchedulerType.Scheduler;
            }
            else
            {
                scheduler.DoctorPatient.PatientId = id;
                scheduler.DoctorPatient.DoctorId = Guid.Parse(HttpContext.GetIdentifier());
                scheduler.Type = SchedulerType.Solicitation;
                scheduler.Specialties = specialties.Split(",").ToList();
            }

            return View(scheduler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SchedulerModel scheduler)
        {
            if (ModelState.IsValid)
            {
                var schedulervalidator = await schedulerService.CreateAsync(scheduler);
                if (!schedulervalidator.Item1.Any())
                {
                    if (scheduler.Type == SchedulerType.Scheduler)
                    {
                        return RedirectToAction(nameof(DetailScheduler), new { schedulerId = schedulervalidator.Item2 });
                    }
                    else
                    {
                        return RedirectToAction(nameof(DetailSolicitation), new { schedulerId = schedulervalidator.Item2 });
                    }
                }
            }

            return View(scheduler);
        }

        public async Task<IActionResult> DetailScheduler(Guid schedulerId)
        {
            var scheduler = await schedulerService.GetConfirmSchedulerAsync(schedulerId);
            return View(scheduler);
        }

        public async Task<IActionResult> DetailSolicitation(Guid schedulerId)
        {
            var solicitation = await schedulerService.GetConfirmSolicitationAsync(schedulerId);
            return View(solicitation);
        }
    }
}

src/ShareCare.App/Views/PatientGuide/Details.cshtml
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Yearly Sales</h3>
                    <canvas id="sales-chart" height="318" style="display: block; height: 255px; width: 510px;" width="637" class="chartjs-render-monitor"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Team Commits</h3>
                    <canvas id="team-chart" height="318" width="637" class="chartjs-render-monitor" style="display: block; height: 255px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Bar chart</h3>
                    <canvas id="barChart" height="425" width="637" class="chartjs-render-monitor" style="display: block; height: 340px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Rader chart</h3>
                    <canvas id="radarChart" height="425" width="637" class="chartjs-render-monitor" style="display: block; height: 340px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Line Chart</h3>
                    <canvas id="lineChart" height="318" width="637" class="chartjs-render-monitor" style="display: block; height: 255px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Doughut Chart</h3>
                    <canvas id="doughutChart" height="318" width="637" class="chartjs-render-monitor" style="display: block; height: 255px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Pie Chart</h3>
                    <canvas id="pieChart" height="425" width="637" class="chartjs-render-monitor" style="display: block; height: 340px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Polar Chart</h3>
                    <canvas id="polarChart" height="425" width="637" class="chartjs-render-monitor" style="display: block; height: 340px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="au-card m-b-30">
                <div class="au-card-inner">
                    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                    <h3 class="title-2 m-b-40">Single Bar Chart</h3>
                    <canvas id="singelBarChart" height="318" width="637" class="chartjs-render-monitor" style="display: block; height: 255px; width: 510px;"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

src/ShareCare.App/Views/PatientGuide/Index.cshtml
@model IEnumerable<ShareCare.Model.Models.SimplePatientModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    h4 {
        top: 99px;
        left: 415px;
        width: 290px;
        height: 35px;
        color: var(--unnamed-color-ffffff);
        text-align: left;
        font: normal normal bold 25px/38px Poppins;
        letter-spacing: 0px;
        color: #FFFFFF;
        opacity: 1;
    }

    h5 {
        top: 139px;
        left: 415px;
        width: 660px;
        height: 28px;
        color: var(--unnamed-color-ffffff);
        text-align: left;
        font: normal normal normal 20px/30px Poppins;
        letter-spacing: 0px;
        color: #FFFFFF;
        opacity: 1;
    }

    th {
        top: 221px;
        left: 525px;
        width: 43px;
        height: 20px;
        text-align: left;
        font: normal normal bold 14px/21px Poppins;
        letter-spacing: 0px;
        color: #3D3D3D;
        opacity: 1;
    }

    tr {
        top: 251px;
        left: 440px;
        width: 771px;
        height: 121px;
        background: var(--unnamed-color-ffffff) 0% 0% no-repeat padding-box;
        background: #FFFFFF 0% 0% no-repeat padding-box;
        box-shadow: 0px 3px 6px #00000029;
        opacity: 1;
    }
</style>

<div class="col-md-12">
    <div class="table-data__tool">
        <div class="table-data__tool-right">
            <h4 style="color: white; top: 99px;">Meu guia de pacientes</h4>
            <h5 style="color:white; top:139px;">Acesse todas as informações que você precisa de seus pacientes</h5>
        </div>
    </div>
    <div class="col">
        <div class="au-card">
            <div class="rs-select2--light rs-select2--md">
                @{var patients = Model.Select(x => x.Name);}
                @Html.DropDownListFor(m => patients, new SelectList(patients), "Nomes", new { @class = "js-select2" })
                <div class="dropDownSelect2"></div>
            </div>
            <div class="rs-select2--light rs-select2--sm">
                <select class="js-select2" name="time">
                    <option selected="selected">Email</option>
                    <option value="">juliane@gmail.com</option>
                    <option value="">a_bittencourt86@gmail.com</option>
                </select>
                <div class="dropDownSelect2"></div>
            </div>
            <div class="rs-select2--light rs-select2--sm">
                <select class="js-select2" name="time">
                    <option selected="selected">Consulta</option>
                    <option value="">Cardiologia</option>
                    <option value="">Pediatria</option>
                </select>
                <div class="dropDownSelect2"></div>
            </div>
            <div class="rs-select2--light rs-select2--sm">
                <select class="js-select2" name="time">
                    <option selected="selected">Horários</option>
                    <option value="">06/09/2020</option>
                    <option value="">07/09/2020</option>
                    <option value="">08/09/2020</option>
                    <option value="">09/09/2020</option>
                </select>
                <div class="dropDownSelect2"></div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <div class="card-name">
                    <table class="table table-data2">
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td width="10%">
                                        <div class="image img-40">
                                            @{ var img = $"{item.SimpleName}.jpg"; }
                                            <img src="~/img/icon/@img" alt="@item.SimpleName" />
                                        </div>
                                    </td>

                                    <td width="30%" style="text-align: left;font: normal normal bold 14px/21px Poppins;letter-spacing: 0px;color: #3D3D3D;">
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>

                                    <td width="15%" class="desc">
                                        @{ string email = item.Contacts.FirstOrDefault(x => x.Type == ContactType.Email).Value;}
                                        <span>@email</span>
                                    </td>
                                    @*<td>
                                    @{ var phones = item.Contacts.Where(x => x.Type == ContactType.Phone).Select(x => x.Value);
                                        string phonesnumbers = string.Join(",", phones);
                                    }
                                    @phonesnumbers
                                </td>*@
                                    <td width="15%">
                                        @item.Specialty
                                    </td>
                                    @*<th> @Html.DisplayFor(modelItem => item.Specialty)</th>*@
                                    <td width="30%">
                                        @Html.ActionLink("", "Details", new { id = item.Id }, new { @style = "margin:10px; color: #1CA5B8;top: 299px;left: 1087px;width: 32px;height: 24px;", @class = "fas fa-chart-bar fa-2x" })
                                        @Html.ActionLink("", "Historic", new { id = item.Id }, new { @style = "margin:10px; color: #1CA5B8;top: 443px;left: 1136px;width: 21px;height: 24px;", @class = "fas fa-book fa-2x" })
                                        @Html.ActionLink("", "Index", "Scheduler", new { id = item.Id, shedulertype = PersonType.Patient, specialties = item.Specialty }, new { @class = "fas fa-calendar-alt fa-2x", @style = "margin:10px;color: #1CA5B8; top: 299px;left: 1174px;width: 21px;height: 24px;" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

src/ShareCare.App/Views/PatientGuide/List.cshtml

@{
    ViewData["Title"] = "List";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Tables</title>

    <!-- Fontfaces CSS-->
    <link href="~/css/font-face.css" rel="stylesheet" />
    <link href="~/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/css/theme.css" rel="stylesheet" />

</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- DATA TABLE -->
                                <div class="table-responsive table-responsive-data2">
                                    <table class="table table-data2">
                                        <tbody>
                                            <tr class="tr-shadow">
                                                <td class="desc">Mauricio Souza</td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Histórico</button>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr class="spacer"></tr>
                                            <tr class="tr-shadow">
                                                <td class="desc">Mauricio Souza</td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Histórico</button>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr class="spacer"></tr>
                                            <tr class="tr-shadow">
                                                <td class="desc">Mauricio Souza</td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Histórico</button>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr class="spacer"></tr>
                                            <tr class="tr-shadow">
                                                <td class="desc">Mauricio Souza</td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Histórico</button>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- END DATA TABLE -->
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title">Agendar</h1>
                </div>
                <div class="modal-body">
                    <form role="form" method="POST" action="">
                        <input type="hidden" name="_token" value="">
                        <div class="form-group">
                            <label class="control-label">Título</label>
                            <div>
                                <input type="text" class="form-control input-lg" name="email" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Médico</label>
                            <div>
                                <input type="text" class="form-control input-lg" name="email" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="rs-select2--light rs-select2--md">
                                <select class="js-select2" name="property">
                                    <option selected="selected">Especialidade</option>
                                    <option value="">Cardiologista</option>
                                    <option value="">Oncologista</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Descrição</label>
                            <div>
                                <input type="text" class="form-control input-lg" name="description" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Início</label>
                            <div>
                                <input type="datetime-local" class="form-control input-lg" name="dateStart">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Término</label>
                            <div>
                                <input type="datetime-local" class="form-control input-lg" name="dateEnd">
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <button type="submit" class="btn btn-success" asp-area="" asp-controller="MedicalGuide" asp-action="SaveSchedule">Confirmar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>

    <!-- Jquery JS-->
    <script src="~/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/vendor/slick/slick.min.js">
    </script>
    <script src="~/vendor/wow/wow.min.js"></script>
    <script src="~/vendor/animsition/animsition.min.js"></script>
    <script src="~/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="~/js/main.js"></script>

</body>

</html>
<!-- end document-->